services:
  sdvxwiki:
    image: sdvxwiki
    ports:
      - "3000:3000"
    environment:
      CHOKIDAR_USEPOLLING: "true"      
      CHOKIDAR_INTERVAL: 10             
      WATCHPACK_POLLING: "true"
      WATCHPACK_POLL_INTERVAL: 10      
    volumes:
      - .:/sdvxwiki
      - /sdvxwiki/node_modules
    stdin_open: true
    tty: true
    command:
      - sh
      - -c
      - |
        echo "           .___                                      "
        echo "  ______ __| _/__  _____  ___     ___________  ____  "
        echo " /  ___// __ |\\  \/ /\  \/  /    /  _ \\_  __ \/ ___\\ "
        echo " \\___ \/ /_/ | \\   /  >    <    (  <_> )  | \/ /_/  >"
        echo "/____  >____ |  \\_/  /__/\\_ \\ /\\ \\____/|__|  \\___  / "
        echo "     \/     \/             \/ \/            /_____/  "
        echo "Press CTRL-C to exit"
        echo "Restart the container to update Pagefind for the search feature after making changes."
        echo -n "Starting..."
        sleep 1
        echo -n "..."; sleep 1
        echo -n "."; sleep 1
        echo -n ".."; sleep 1
        echo ""
        npm run build && npm run dev
